axon:
  eventhandling:
    processors:
      amqpEvents:
        source: orderEvents

  amqp:
    exchange: ShipmentEvents

# Spring properties
#spring:
#  application:
#     name: order-service
#
## Discovery Server Access
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/
#
## HTTP Server
#server:
#  port: 2222   # HTTP (Tomcat) port
